<img
    src="{$inputDetails.src}"
    height="{$inputDetails.height}"
    width="{$inputDetails.width}"
    alt="{$inputDetails.alt}"
    title="{$inputDetails.title}"
    class=""
    id="{$inputDetails.id}"
    name="{$inputDetails.name}"/>